version: "3.8"

services:
    database:
        restart: always
        image: postgres
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - strike_postgres:/var/lib/postgresql/data

    web:
        build: .
        command: >
            sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"
        ports:
            - "5000:5000"
        depends_on:
            - database
        environment:
            - FLASK_APP=app.app:create_app
            - FLASK_ENV=development
        volumes:
            - .:/usr/src/app

volumes:
    strike_postgres:
