"""users and tasks tables

Revision ID: 2eaa76eb09a3
Revises: 
Create Date: 2023-11-16 23:56:20.334424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eaa76eb09a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_unique_constraint('task_table_const', ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_table_const', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_table_const', type_='unique')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_table_const', type_='unique')

    # ### end Alembic commands ###
