"""Users and Tasks table

Revision ID: 4464b888cb23
Revises: 
Create Date: 2023-11-09 21:46:47.317655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4464b888cb23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_updated_by'), ['updated_by'], unique=False)
        batch_op.create_unique_constraint('tasks_unq_constraint', ['id'])
        batch_op.create_foreign_key('unq_task_updated_contraint', 'user', ['updated_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('unq_task_created_constraint', 'user', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_unq_constraint', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_unq_constraint', type_='unique')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('unq_task_created_constraint', type_='foreignkey')
        batch_op.drop_constraint('unq_task_updated_contraint', type_='foreignkey')
        batch_op.drop_constraint('tasks_unq_constraint', type_='unique')
        batch_op.drop_index(batch_op.f('ix_task_updated_by'))
        batch_op.drop_index(batch_op.f('ix_task_created_by'))
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
